### ISSUE TITLE
Ctrl+C doesn't work

### ISSUE THREAD

**Issue by Enivex** [user202729/tex-fast-recompile#15]
If I press Ctrl+C to kill the process, nothing happens.

(Potentially another Windows specific issue?)

Edit: Ctrl+Pause/Break works though

**Comment by Enivex** [comment]
Ctrl+C now works, but simultaneously gives this error

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\tex_fast_recompile.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\tex_fast_recompile\__main__.py", line 580, in main
    recompile_preamble=q.get(timeout=1)
                       ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "C:\Python311\Lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Python311\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\redacted\\AppData\\Local\\Temp\\.tex-fast-recompile-tmp\\3840-0zqfjug3\\main.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\tempfile.py", line 878, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\redacted\\AppData\\Local\\Temp\\.tex-fast-recompile-tmp\\3840-0zqfjug3\\main.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\weakref.py", line 666, in _exitfunc
    f()
  File "C:\Python311\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\tempfile.py", line 894, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "C:\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python311\Lib\tempfile.py", line 881, in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
  File "C:\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\shutil.py", line 603, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Python311\Lib\shutil.py", line 600, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
         ^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\redacted\\AppData\\Local\\Temp\\.tex-fast-recompile-tmp\\3840-0zqfjug3\\main.log'
```
